"""Initial migration

Revision ID: 7369c8cf7f90
Revises:
Create Date: 2024-12-26 17:24:31.766546

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7369c8cf7f90"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
