"""create user sub

Revision ID: f1ee81459050
Revises: 19fe453b88d0
Create Date: 2025-02-05 20:24:36.652781

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f1ee81459050"
down_revision: Union[str, None] = "19fe453b88d0"
branch_labels: Union[
    str,
    Sequence[str],
    None,
] = None
depends_on: Union[
    str,
    Sequence[str],
    None,
] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
