"""add sub on cat

Revision ID: a3c422a249a2
Revises: 8cf0006f449d
Create Date: 2025-07-25 17:53:54.290828

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3c422a249a2"
down_revision: Union[str, None] = "8cf0006f449d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_subscriptions", sa.Column("category_id", sa.Integer(), nullable=False))
    op.drop_constraint("user_subscriptions_sub_category_id_fkey", "user_subscriptions", type_="foreignkey")
    op.create_foreign_key(None, "user_subscriptions", "categories", ["category_id"], ["id"], ondelete="CASCADE")
    op.drop_column("user_subscriptions", "sub_category_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_subscriptions", sa.Column("sub_category_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "user_subscriptions", type_="foreignkey")
    op.create_foreign_key(
        "user_subscriptions_sub_category_id_fkey", "user_subscriptions", "sub_categories", ["sub_category_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("user_subscriptions", "category_id")
    # ### end Alembic commands ###
