name: LeitMind CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Update lock file
        working-directory: backend/LeitMind
        run: |
          poetry lock

      - name: Install dependencies
        working-directory: backend/LeitMind
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Build Docker Image
        run: docker build -t my-app:latest .

      - name: Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          docker tag my-app:latest $DOCKER_USERNAME/my-app:latest
          docker push $DOCKER_USERNAME/my-app:latest

      - name: Deploy on Netlify
        uses: netlify/actions/deploy@v1
        with:
          publish-dir: ./web/leitMind 
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}